export const aboutContent = {
	en: {
		aboutCopyright: 'A. R. MANCEBO ©2026',
		aboutBio: 'My multidisciplinary background allows me to create complex designs with a holistic perspective, connecting different areas and tools. My work ranges from motion graphics to ux/ui, video editing, photography and 3d modelling.',
		aboutCV: 'DOWNLOAD CV',
		aboutPdf: 'PORTFOLIO PDF -->',
		aboutTitleStack: 'STACK',
		aboutTitleSoftware: 'SOFTWARE',
		aboutTitleStudies: 'STUDIES',
		aboutTitleDesign: 'CONTACT',
		aboutTitleUxuiWeb: 'UX/UI AND WEB DESIGN',
		aboutTitleVisualDesign: 'VISUAL DESIGN',
		aboutTitleMotion3d: '3D AND MOTION',
		aboutTitleAiWorkflow: 'AI WORKFLOW AND OPTIMIZATION',
		aboutListStack: ['HTML & CSS', 'JavaScript', 'React & Next.js', 'Node.js & Express', 'MongoDB'],
		aboutListUxuiWeb: ['Figma', 'Webflow', 'Framer'],
		aboutListVisualDesign: ['Adobe Illustrator', 'Photoshop', 'InDesign', 'Affinity', 'Canva'],
		aboutListMotion3d: ['After Effects', 'Premiere', 'Blender', 'Unity'],
		aboutListAiWorkflow: ['Miro', 'Notion', 'Copilot', 'ChatGPT', 'Claude'],
		aboutListStudies: ['Fullstack Web Development', 'UX/UI Design', 'Integral Design'],
		aboutListCredits: ['alek.rmancebo@gmail.com']
	},
	es: {
		aboutCopyright: 'A. R. MANCEBO ©2026',
		aboutBio: 'Mi formación multidisciplinar me permite crear diseños complejos con una perspectiva holística, conectando diferentes áreas y herramientas. Mi trabajo varía desde motion graphic hasta ux/ui, fotografía, edición de video y modelización 3D.',
		aboutCV: 'DESCARGAR CV',
		aboutPdf: 'PORTFOLIO PDF -->',
		aboutTitleStack: 'STACK',
		aboutTitleSoftware: 'SOFTWARE',
		aboutTitleStudies: 'ESTUDIOS',
		aboutTitleDesign: 'CONTACTO',
		aboutTitleUxuiWeb: 'UX/UI Y DISENO WEB',
		aboutTitleVisualDesign: 'DISENO VISUAL',
		aboutTitleMotion3d: '3D Y MOTION',
		aboutTitleAiWorkflow: 'WORKFLOW Y OPTIMIZACION IA',
		aboutListStack: ['HTML & CSS', 'JavaScript', 'React & Next.js', 'Node.js & Express', 'MongoDB'],
		aboutListUxuiWeb: ['Figma', 'Webflow', 'Framer'],
		aboutListVisualDesign: ['Adobe Illustrator', 'Photoshop', 'InDesign', 'Affinity', 'Canva', 'Procreate'],
		aboutListMotion3d: ['After Effects', 'Premiere', 'Blender', 'Unity'],
		aboutListAiWorkflow: ['Miro', 'Notion', 'Copilot', 'ChatGPT', 'Claude'],
		aboutListStudies: ['Desarrollo Web Fullstack', 'Diseño UX/UI', 'Diseño Integral'],
		aboutListCredits: ['alek.rmancebo@gmail.com']
	}
};
